spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    url: jdbc:postgresql://localhost:5432/Angels-Insurance-Inc
    password: sh.25002500Pp
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  security:
    user:
      name: shareef
      password: pass123



#Hibernate property values are: create, update, create-drop, validate and none:
#  create – Hibernate first drops existing tables, then creates new tables
#  update – the object model created based on the mappings (annotations or XML) is compared with the existing schema, and then Hibernate updates the schema according to the diff. It never deletes the existing tables or columns even if they are no more required by the application
#  create-drop – similar to create, with the addition that Hibernate will drop the database after all operations are completed. Typically used for unit testing
#  validate – Hibernate only validates whether the tables and columns exist, otherwise it throws an exception
#  none – this value effectively turns off the DDL generation


server:
  port: 8088

jwt:
  secret: 7D3B8F1C5A9E3B0E4A1C8B7FBB5D2A3E1F9C4A8B2E1D7E7B1A3C5E8F9A7D4E3C
  token:
    expiration: 86400000 # 1 day in milliseconds